### ISSUE TITLE
Perform inference on embedding

### ISSUE THREAD

**Issue by tbass134** [qiuqiangkong/audioset_classification#1]
Hello,
Forgive me as this is a novice question.
Is it possible to run a classification prediction on a given audio embedding?
It looks like this supports training as well as get_avg_stats.

**Comment by qiuqiangkong** [comment]
Yes you could predict on a given audio embedding. You should extract audioset embedding feature first and then apply the model.


Best wishes,


Qiuqiang

________________________________

**Comment by tbass134** [comment]
OK, thanks!
