### ISSUE TITLE
Missing files to run statistical operations

### ISSUE THREAD

**Issue by Katchau** [qiuqiangkong/audioset_classification#2]
Hi there!

I'm trying to run your project but I can't run the statistical part as it says that it's missing a folder  'probs' and its content. I also tried running other project you contributed to (https://github.com/ChangsongYu/Eusipco2018_Google_AudioSet) and I'm getting the same error.

Ty for your time!

**Comment by qiuqiangkong** [comment]
Hi, the folder 'probs' should be created once you run the code. Could you point out which line does this error occur?


Best wishes,


Qiuqiang

________________________________

**Comment by Katchau** [comment]
Hey thanks for the quick reply!

```
Traceback (most recent call last):
  File "keras/main.py", line 221, in <module>
    utilities.get_avg_stats(args)
  File "/home/jonas/Documents/nn/keras/../utils/utilities.py", line 151, in get_avg_stats
    prob_names = os.listdir(prob_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'probs/main/balance_type=balance_in_batch/model_type=decision_level_single_attention/test'
```

I also just realized I got a memory error while running the trainning process, which might be the reason no files are there.

```
Traceback (most recent call last):
  File "keras/main.py", line 215, in <module>
    train(args)
  File "keras/main.py", line 170, in train
    core.train(args)
  File "/home/jonas/Documents/nn/keras/core.py", line 108, in train
    unbal_train_hdf5_path)
  File "/home/jonas/Documents/nn/keras/../utils/utilities.py", line 61, in load_data
    x = hf['x'][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/jonas/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 562, in __getitem__
    arr = numpy.ndarray(mshape, new_dtype, order='C')
MemoryError
```

I have both errors on both programs so if you have any ideas I'd be appreciated!

**Comment by qiuqiangkong** [comment]
Hi, did you run the training first?


Best wishes,


Qiuqiang

________________________________

**Comment by Katchau** [comment]
Yes and I got the Memory Error message I wrote on the previous reply.

**Comment by qiuqiangkong** [comment]
It looks like that the loading error is caused by loading hdf5 is different in python 2 and 3. The code is developed with python2. I will try to fix it and let you know!


Best wishes,


Qiuqiang

________________________________

**Comment by Katchau** [comment]
Thank you very much! Update me when you can please :)

**Comment by Katchau** [comment]
Hi once again!

I've been trying to run your project again using python2 and I can't seem to find a working version of it as I always get a "Failed to load the native TensorFlow runtime" due to some modules not being found. Do you mind sharing the version you used so I can try again?

best regards,

**Comment by qiuqiangkong** [comment]
Hi,

    Sorry for the delayed reply! It looks you are using Keras with Tensorflow as backend.

    My configuration is the following and they are work.

    Python3 + Tensorflow 1.11
    Python2 + Tensorflow 1.11

    It might be some of your configurations is not set. For example, did you install tensorflow correctly?


Best wishes,


Qiuqiang

________________________________

**Comment by Katchau** [comment]
Yes exactly, I'm using Tensorflow with Keras.

I installed the latest python version and installed tensorflow via pip command (pip install tensorflow).

I'm not sure if this will enable to use tensorflow with the gpu (as you need to run in order to use the cuda processors) so that's why I was asking what version of tensorflow you were using. If this isn't the way you installed Tensorflow please inform me!

best regards,

**Comment by qiuqiangkong** [comment]
Hi,

    I installed via anaconda. Have you tried to run some keras example code such as MNIST classification and have a look if it works?


Best wishes,


Qiuqiang

________________________________

**Comment by Katchau** [comment]
I'll try and let you know !

**Comment by Katchau** [comment]
Hi again!

I've managed to properly setup everything, turns out it was an outdated graphical driver. 

However now I'm facing a memory problem due to the fact of the training process creating too much temporary GBs of memory, and I couldn't finish running up everything. Do you have an idea of how much memory the whole process takes? I can try and run it on an external drive if the value doesn't surpass 200 Gigs.

Best regards,
