### ISSUE TITLE
training details

### ISSUE THREAD

**Issue by sourav22899** [qiuqiangkong/audioset_classification#4]
Hi,
Can you please tell specifications of the machine on which you trained the model ? I am using the following command for training:
`%run -i 'keras/main.py' --data_dir='dataset/' --mini_data --workspace='pwd' --model_type='decision_level_single_attention' 'train'`
I am using a 12 GB RAM and NVIDIA Tesla K40 GPU for training. I am getting RAM overflow issue.

**Comment by qiuqiangkong** [comment]
Hi, the experiment is runned on a single card TitanX GPU with 12 GB RAM. It should only takes very few RAM usage. You could check if your RAM is not fully occupied by other programs.


Best wishes,


Qiuqiang

________________________________

**Comment by sourav22899** [comment]
Thanks, i will check that. And would please tell the approximate time for training the model ?

**Comment by qiuqiangkong** [comment]
The training should be around 1-2 hours on a single TitanX card.


Best wishes,


Qiuqiang

________________________________

**Comment by sourav22899** [comment]
Thanks a lot.

Sourav
