### ISSUE TITLE
Role of 'time_steps'

### ISSUE THREAD

**Issue by sourav22899** [qiuqiangkong/audioset_classification#5]
Hi Qiuqiang,
    
    def train(args):    
        model_type = args.model_type

        time_steps = 10
        freq_bins = 128
        classes_num = 527

       # Hyper parameters
        hidden_units = 1024
        drop_rate = 0.5
        batch_size = 500

Can you please explain the role of time_steps in the code? I guess it is present because the Google audioset dataset comprises of 128 dimensional embedding sampled at 1Hz and each audio sample is approximately of 10 seconds length, so that would account for 10 time_steps.
Am I on right track ? If yes, then how do you account for the audio clips that are less than 10 seconds in duration (say 6 seconds or so)?

Thanks in advance.

**Comment by qiuqiangkong** [comment]
Hi Sourav,

    You are right. The time_steps=10 comes from 10 seconds audio clip. For those audio clips shorter than 10 seconds, they are padded with silence to 10 seconds.


Best wishes,


Qiuqiang

________________________________
