### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by hackerekcah** [qiuqiangkong/audioset_classification#7]
Hi Qiuqiang, nice work!

Is there any possibility I can get your trained weights, the best of the models if possible.

Thanks!

**Comment by qiuqiangkong** [comment]
Hi, thanks! Unfortunately we did not keep the trained models considering it only takes hours to retrain.


Best wishes,


Qiuqiang

________________________________

**Comment by hackerekcah** [comment]
OK, I will try to retrain, Thanks!
